
CREATE TABLE CONSULTA
(
	ID_CONSULTA INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	NOME_PACIENTE VARCHAR(50) NOT NULL, 	
 	DAT_NASCIMENTO DATE NOT NULL ,
	DATAINICIO DATETIME NOT NULL,
	DATAFIM DATETIME NOT NULL,
	OBSERVACAO VARCHAR(300) NULL
);