// <auto-generated />
using System;
using AgendaMedicaAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgendaMedicaAPI.Migrations
{
    [DbContext(typeof(ConsultaContext))]
    partial class ConsultaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AgendaMedicaAPI.Models.Consulta", b =>
                {
                    b.Property<int>("Id_Consulta")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Dat_Fim_Consulta")
                        .HasColumnType("DateTime");

                    b.Property<DateTime>("Dat_Inicio_Consulta")
                        .HasColumnType("DateTime");

                    b.Property<DateTime>("Dat_Nascimento")
                        .HasColumnType("Date");

                    b.Property<string>("Nome_Paciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id_Consulta");

                    b.ToTable("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
